config/routes.rb
Genesis::Application.routes.draw do

  resources :members
  resources :wishes
  resources :items
  resources :boards
  resources :craftmen
  resources :recipies
  resources :crafting
  

  root :to => 'members#start'

end

app/controllers/recipies_controller.rb
class RecipiesController < ApplicationController

  def show
    @item = Item.find(params[:id])
    @recipies = Recipie.find(:all, :conditions => {:item_id => @item.id })
    @composants = Recipie.find(:all, :conditions => {:ingredient_id => @item.id })
  end

  def create
    @recipie = Recipie.new(params[:recipie])
    @recipie.save
    
    redirect_to recipy_path(@recipie.item)
  end
  
  def destroy
    @recipie = Recipie.find(params[:id])
    @item = @recipie.item
    @recipie.delete
    
    redirect_to recipy_path(@item)
    
  end
end

app/helpers/recipies_helper.rb
module RecipiesHelper
end

app/views/recipies/_new.html.erb
<div class="bloc4 left">
  <div class="titre"><h2>Ajouter un ingrédient</h2></div>
  <table style="height: 70px">
<%= form_for(Recipie.new, :html => { :class => "left"}) do |f| %>
    <%= f.hidden_field :item_id,  :value => item_id %>
    <tr> 
      <td>Ingrédient</td> 
      <td><%= text_field_with_auto_complete :recipie, :ingredient_name, { :size => 25 }, { :url => items_path(:js), :method => :get, :with => "'search=' + element.value" } %></td>
    </tr>
    <tr>
      <td>Nombre</td> 
      <td><%= f.number_field :number, :size => 1 %></td>
    </tr>
    <tr> 
      <td></td><td><%= f.submit "Ajouter" %></td>
    </tr>
<% end %>
</table>
</div>

app/views/recipies/_new2.html.erb
<div class="bloc4 left">
  <div class="titre"><h2>Ajouter comme composant de </h2></div>
  <table style="height: 70px">
<%= form_for(Recipie.new, :html => { :class => "left"}) do |f| %>
    <%= f.hidden_field :ingredient_id,  :value => ingredient_id %>
    <tr> 
      <td>Item</td> 
      <td><%= text_field_with_auto_complete :recipie, :item_name, { :size => 25 }, { :url => items_path(:js), :method => :get, :with => "'search=' + element.value" } %></td>
    </tr>
    <tr>
      <td>Nombre</td> 
      <td><%= f.number_field :number, :size => 1 %></td>
    </tr>
    <tr> 
      <td></td><td><%= f.submit "Ajouter" %></td>
    </tr>
<% end %>
</table>
</div>

app/views/recipies/_view.html.erb
<div class="bloc left">
  <div class="titre"><h2>Liste des ingrédients</h2></div>
  <table style="width: 100%">
    <% recipies.each do |recipie| %>
    <tr>
      <td style="width: 50px"><%= recipie.number %></td>
      <td><%= image_tag recipie.ingredient.url, :size => "25x25" unless recipie.ingredient.url_missing? %></td>  
      <td><%= link_to recipie.ingredient.name, recipy_path(recipie.ingredient) %></td>
      <%= form_for(recipie, :method => 'DELETE') do |f| %>
      <td><%= image_submit_tag 'delete.png' %></td>
      <% end %>
    </tr>  
    <% end %>
  </table>
</div>

app/views/recipies/_view2.html.erb
<div class="bloc left">
  <div class="titre"><h2>Composants de</h2></div>
  <table style="width: 100%">
    <% recipies.each do |recipie| %>
    <tr>
      <td style="width: 50px"><%= recipie.number %></td>  
      <td><%= image_tag recipie.item.url, :size => "25x25" unless recipie.item.url_missing? %></td>  
      <td><%= link_to recipie.item.name, recipy_path(recipie.item) %></td>  
    </tr>  
    <% end %>
  </table>
</div>

app/views/recipies/show.html.erb
<div id="board" class="section"><%= link_to image_tag('board.png', :size => '55x30'), boards_path %>
  <div class="nom"><%= image_tag(@item.url) unless @item.url_missing? %><h1>Item: <%= @item.name %></h1></div>
  <div class="nom perso"><%= link_to("Voir les autres recettes du " + @item.crafting.name, crafting_path(@item.crafting_id)) unless @item.crafting_id.nil? %></div>    
  <div class="perso"><%= render :partial => "members/new" %></div>    
</div>
<div class="section">
  <%= render :partial => "items/edit", :locals => { :item => @item } %>
  <%= render :partial => "recipies/view", :locals => { :recipies => @recipies } %>
  <%= render :partial => "recipies/new", :locals => { :item_id => @item.id } %>
</div>
<div class="section">
  <%= render :partial => "items/new" %>
  <%= render :partial => "recipies/view2", :locals => { :recipies => @composants } %>
  <%= render :partial => "recipies/new2", :locals => { :ingredient_id => @item.id } %>
</div>