config/routes.rb
Genesis::Application.routes.draw do

  resources :members
  resources :wishes
  resources :items
  resources :boards
  resources :craftmen
  resources :recipies
  resources :crafting
  

  root :to => 'members#start'

end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :wishes, :class_name => 'Wishe' 
  has_many :craftmen 
  has_many :craftings, :through => :craftmen, :class_name => 'Crafting' 
  
  attr_accessible :phpbb_id, :name

  def crafting_level?(crafting_id, level)
    crafting(crafting_id).level >= level unless crafting(crafting_id).nil?
  end

  def crafting(crafting_id)
    array = self.craftmen.select{ |craftman| craftman.crafting_id == crafting_id}
    return array[0] unless array.empty?
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  respond_to :html,:js 

  def index
    @members = Member.find(:all, :conditions => ['name ILIKE ?', "%#{params[:search]}%"])
  end

  def create
    
    unless params[:member][:name].empty?
      @member = Member.find_by_name(params[:member][:name])
    
      redirect_to(@member.nil? ? boards_path : member_path(@member))
    else
      redirect_to boards_path
    end
  end
  
  def show
    if params[:id] == "0"
      @member = Member.find_by_phpbb_id(cookies[:phpbb3_hjy2a_u])
    else  
      @member = Member.find(params[:id])
    end
  
    @craftings = Hash.new
    @member.craftmen.each { |craftman| @craftings[craftman.crafting_id] = Wishe.find_crafting(craftman.crafting_id)}
        
        
    respond_with @member
  end
  
  def start
    if cookies[:phpbb3_hjy2a_u].nil? || cookies[:phpbb3_hjy2a_u].empty?
      redirect_to boards_path
    else
      @member = Member.find_by_phpbb_id(cookies[:phpbb3_hjy2a_u])
      
      if @member.nil?
        @member = Member.create(:name => params[:id].nil? ? "New member" : params[:id], :phpbb_id => cookies[:phpbb3_hjy2a_u])
      end
      
      @craftings = Hash.new
      @member.craftmen.each { |craftman| @craftings[craftman.crafting_id] = Wishe.find_crafting(craftman.crafting_id)}
        
        
      respond_with(@member) do |format|
        format.html { render 'show' }
      end
    end
  end
  
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_new.html.erb
<div class="bloc">
  <div class="titre"><h2>Accès à <%= link_to "votre page", member_path(0) %> ou consulter une autre page</h2></div>
  <table><tr>
  <%= form_for(Member.new) do |f| %>
    <td><%= text_field_with_auto_complete :member, :name, { :size => 35 }, { :url => members_path(:js), :method => :get, :with => "'search=' + element.value" } %></td> 
    <td><%= f.submit "Consulter", :method => 'POST' %></td>
  <% end %>
  </tr></table>
</div>

app/views/members/_show.html.erb
<div class="bloc4 left">
  	<div class="titre"><h2>Professions</h2>
    <table><tr>
      <td>Métier</td>
      <td width="120px"></td>
      <td>Niveau</td>    
    </tr></table>
  	</div>
	<table>
      <% member.craftmen.each do |craftman| %>
	  <tr>
      <%= form_for(craftman, :method => 'DELETE') do |f| %>
      <td><%= image_submit_tag 'delete.png' %></td>
      <% end %>
      <td><%= image_tag craftman.craft_image, :size => "25x25" unless craftman.craft_image.nil? %></td>
      <%= form_for(craftman, :html => { :class => "left"}) do |f| %>
      <td style="width: 150px"><%= link_to craftman.craft_name, crafting_path(craftman.crafting_id) %></td><td><%= f.number_field :level, :size => 1 %></td><td><%= image_submit_tag 'save.png', :method => 'PUT', :class => "button" %></td>
      <% end %>
	  <td></td>
      </tr>
	  <% end %>

      <tr></tr>
      <tr>  
      <td></td>
      <td></td>
      <%= form_for(Craftman.new) do |f| %>
      <%= f.hidden_field :member_id,  :value => member.id %>
      <td style="width: 150px"><%= f.collection_select :crafting_id, Crafting.find(:all), :id, :name %></td><td><%= f.number_field :level, :size => 1 %></td><td colspan="3"><%= f.submit "Ajouter", :method => 'POST' %></td>
      <% end %>
      </tr>
    </table>
</div>

app/views/members/_wishes.html.erb
<div class="bloc left">
  <div class="section">
    <div class="left color"><h2>Items souhaités</h2></div>
    <%= render :partial => "wishes/new", :locals => { :member_id => id } %>
  </div>
  <div class="titre"></div>
  <div class="section">
    <table class="left" width="50%">
    <tr><td colspan="5" class="titre">Item craftable</td></tr>
    <% wishes.each do |wish| %>
    <tr><%= render :partial => "wishes/show", :locals => { :wishe => wish, :update => false } if wish.item.craftable? %></tr>
    <% end %>
    </table>

    <table class="left" width="50%">
    <tr><td colspan="5" class="titre">Matériaux</td></tr>
    <% wishes.each do |wish| %>
    <tr><%= render :partial => "wishes/show", :locals => { :wishe => wish, :update => true } if wish.item.material? %></tr>
    <% end %>
    </table>

  </div>
</div>

app/views/members/_workes.html.erb
<div class="bloc left">
  <div class="titre"><h2>Items à réaliser</h2>
    <table><tr>
      <td>Métier</td>
      <td class="td_indent"></td>
      <td>Items</td>    
      <td width="150px"></td>
      <td>Niveau</td>    
      <td class="td_indent"></td>
      <td>Status</td>    
    </tr></table>
  </div>
  <table style="width: 100%">
    <% craftings.each_key do |key| %>
    <tr>
      <% unless craftings[key].empty? %>  
      <% crafting = craftmen.select {|v| v.crafting_id == key}[0].crafting %>
      <td><%= image_tag crafting.icone, :size => "25x25" unless crafting.icone.nil? %></td>
      <td colspan="3"><%= link_to crafting.name, crafting_path(crafting.id)  %></td>
      <% end %>
    </tr>
    <% craftings[key].each do |wish| %>
    <tr>
      <td class="td_indent"></td>  
      <td><%= image_tag wish.url, :size => "25x25" unless wish.url.empty? %></td>
      <td><%= link_to wish.name, recipy_path(wish.item_id) %></td>
      <td class="td_indent"></td>  
      <td style="width: 50px"><%= wish.niveau %></td>
      <%= form_for(wish, :remote => true) do |f| %>
      <td><%= select_tag :statut, options_for_select(["Recherche", "Disponible"]) %></td>
      <td><%= image_submit_tag 'save.png', :method => 'PUT', :class => "button" %></td>
      <% end %>
    </tr>
    <% end %>
    <% end %>
  </table>
</div>

app/views/members/index.js.erb
<%= auto_complete_result @members, :name %>

app/views/members/show.html.erb
<div id="board" class="section"><%= link_to image_tag('board.png', :size => '55x30'), boards_path %>
  <div class="nom"><h1><%= @member.name %></h1></div>
  <div class="perso"><%= render :partial => "items/show" %></div>    
</div>

<div class="section">
  <%= render :partial => "members/show", :locals => { :member => @member } %>
  <%= render :partial => "members/workes", :locals => { :craftings => @craftings, :craftmen => @member.craftmen } %>
</div>

<div class="section">
  <%= render :partial => "items/new" %>
  <%= render :partial => "members/wishes", :locals => { :wishes => @member.wishes, :id => @member.id} %>
</div>